name: Compilar APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Instalar dependencias
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev libffi-dev cmake
        pip install --upgrade buildozer cython
    - name: Configurar buildozer
      run: |
        # Si no existe el archivo .spec, lo crea
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        # Configurar permisos para que Avi tenga "poder"
        sed -i 's/#android.permissions = .*/android.permissions = INTERNET,ACCESS_NETWORK_STATE,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE,FOREGROUND_SERVICE,WAKE_LOCK,RECEIVE_BOOT_COMPLETED/' buildozer.spec
        sed -i 's/android.api = .*/android.api = 33/' buildozer.spec
        sed -i 's/android.minapi = .*/android.minapi = 21/' buildozer.spec
    - name: Compilar APK
      run: |
        buildozer -v android debug
    - name: Subir APK
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: bin/*.apk
