name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev libffi-dev cmake
          pip install --upgrade buildozer cython
          
      - name: Build with Buildozer
        env:
          BUILDOZER_ALLOW_ROOT: 1
        run: |
          buildozer init
          yes | buildozer -v android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mi_App_APK
          path: bin/*.apk
